module.exports = [
  "Direction matters more than speed.",
  "Consistency is a superpower.",
  "Work hard silently, speak with results.",
  "Reputation is a form of currency.",
  "Relationships are long-term leverage.",
  "Clarity comes from doing, not thinking.",
  "Progress beats perfection.",
  "Tiny habits create massive change.",
  "Action reduces fear.",
  "Start before you feel ready.",
  "More doing, less doubting.",
  "Do it badly if you must—just begin.",
  "If it matters, schedule it.",
  "Deadlines turn ideas into reality.",
  "One skill mastered beats ten half-learned.",
  "Long-term people win long-term games.",
  "Curiosity compounds like interest.",
  "Think independently, act consistently.",
  "Attention is your most valuable resource.",
  "Protect your focus like a fortress.",
  "Boundaries are a form of self-respect.",
  "You teach others how to treat you.",
  "Choose calm over chaos.",
  "Solitude sharpens perspective.",
  "Let go of what you can’t control.",
  "Rest is a strategy, not weakness.",
  "Slow down to understand faster.",
  "No one is coming to save you.",
  "Own your mornings; they shape your life.",
  "Your habits speak louder than your intentions.",
  "Discipline creates freedom.",
  "Risk is the entrance fee to opportunity.",
  "Simple scales; complicated fails.",
  "When confused, zoom out.",
  "Decisions are bets on your future self.",
  "You can’t optimize what you don’t measure.",
  "Be the person who takes notes.",
  "Think long-term, execute short-term.",
  "Don’t confuse motion with progress.",
  "Avoid zero-sum thinking.",
  "Most limits are self-imposed.",
  "Independent thinking is a superpower.",
  "Your direction determines your destination.",
  "Emotion is information, not instruction.",
  "Distance creates clarity.",
  "Stop chasing; start attracting.",
  "Real connection feels safe, not dramatic.",
  "Silence is an answer.",
  "Honesty saves everyone’s time.",
  "Not everyone deserves access to you.",
  "Replace expectation with appreciation.",
  "Growth begins where comfort ends.",
  "Mastery tolerates boredom.",
  "Wealth is measured in freedom.",
  "Money amplifies identity, not character.",
  "Adaptation beats prediction.",
  "Choose problems worth solving.",
  "High agency beats high IQ.",
  "Skills have longer shelf lives than jobs.",
  "Your systems determine your success.",
  "Most fear is imagination.",
  "Simplify your decisions.",
  "Your mind is your primary environment.",
  "Less noise, more signal.",
  "Calmness improves decision quality.",
  "You become your repeated choices.",
  "Meaning comes from direction.",
  "Focus on inputs; let outputs follow.",
  "Don’t outsource your happiness.",
  "Assume goodwill, verify behavior.",
  "Learn from patterns, not predictions.",
  "Small steps compound.",
  "Insight follows action.",
  "Argue to understand, not to win.",
  "Your work reveals you before your title does.",
  "Energy matters more than time.",
  "Most worries are irrelevant in hindsight.",
  "Listen to tone, not just words.",
  "Choose the future version of yourself.",
  "Your habits shape your identity.",
  "Calm is a competitive advantage.",
  "Comfort kills potential.",
  "Less emotion, more motion.",
  "Invest in skills, not status.",
  "Everything costs something.",
  "Behavior changes identity.",
  "Slow progress is still progress.",
  "Execution creates momentum.",
  "Your standards define your life.",
  "Confidence comes from evidence.",
  "Momentum multiplies effort.",
  "Clarity is magnetic.",
  "Quiet effort builds loud results.",
  "Be who you needed when you were younger.",
  "Long-term thinking shortens the path.",
  "Growth requires discomfort.",
  "Attention determines reality.",
  "Direction first, acceleration later.",
  "Your future depends on what you practice today.",
  "Do hard things; they make you easier to trust."
];